title: AICS Modeling 
description: Data stories from the Allen Institute for Cell Science
theme: jekyll-theme-minimal
url: http://allencellmodeling.github.io
show_downloads: true

permalink: "/:year/:title"
