title: AICS Modeling 
description: Brief, and sometimes rough, data stories from the modeling group at the <a href='http://www.allencell.org'>Allen Institute for Cell Science</a>
theme: jekyll-theme-minimal
url: http://allencellmodeling.github.io
show_notebook_downloads: true

permalink: "/:year/:title"
